// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCOSGeirb8fvNVfhh4fM7zyfdu3rDmjil4',
    appId: '1:133336386533:android:e3dc3b696aad597f943d0c',
    messagingSenderId: '133336386533',
    projectId: 'speedtaxi-7af58',
    storageBucket: 'speedtaxi-7af58.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDe7EjyidSFZdq38OE1FO1v7nuQ9NVaD98',
    appId: '1:133336386533:ios:977ebe484d4929e5943d0c',
    messagingSenderId: '133336386533',
    projectId: 'speedtaxi-7af58',
    storageBucket: 'speedtaxi-7af58.appspot.com',
    androidClientId: '133336386533-67h3eq66pgna2l90732vjnnjkq1fetjl.apps.googleusercontent.com',
    iosClientId: '133336386533-mb5o3vkgnp089q2tula0i7lnh98agkke.apps.googleusercontent.com',
    iosBundleId: 'com.branchminer.flubbercustomer',
  );
}
